apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-srv
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: 'true'
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:eu-west-1:009403946339:certificate/00c6fb98-f09f-4be6-a508-797978d295e7
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: https
    service.beta.kubernetes.io/aws-load-balancer-ssl-negotiation-policy: 'ELBSample-OpenSSLDefaultNegotiationPolicy'
spec:
  rules:
    - host: 'voting-api.mh.codes'
      http:
        paths:
          - path: /users/?(.*)
            pathType: Prefix
            backend:
              serviceName: users-srv
              servicePort: 3000
          - path: /causes/?(.*)
            pathType: Prefix
            backend:
              serviceName: causes-srv
              servicePort: 3000
          - path: /allocations/?(.*)
            pathType: Prefix
            backend:
              serviceName: allocations-srv
              servicePort: 3000
