name: allocations-deploy

on:
  push:
    branches:
      # push is triggered when a PR is merged in to master
      - master

jobs:
  # this is the job id and can be whatever we want
  build:
    # comes with docker pre installed
    runs-on: ubuntu-latest
    steps:
      # uses tells the job to retrieve a community action
      # this action checks out the repository and downloads it
      # to the runner so we can run further actions / commands against the code
      - uses: actions/checkout@v2

      # Connect to AWS kubernetes cluster
      - run: aws --version
      - run: kubectl config get-contexts

      # restart the deployment
